### PR TITLE
Feature/zohra thabti/add docker build push step to ci

### PR DESCRIPTION
**Pull request by ThabtiZahra**
Feature/zohra thabti/add docker build push step to ci

### CODE REVIEW

**Comment by ThabtiZahra** [comment]
Feature/zohra thabti/add docker build push step to ci

**Comment by idriss-mezguich** [comment]
Did you test the pipeline run ?

**Comment by idriss-mezguich** [comment]
`file2` isn't required, please remove it.

**Comment by idriss-mezguich** [comment]
The assignment is to merge the PR to the `dev` branch, not `main`.

**Pull request closed without merging**
